In [2]:
import numpy as np

# 配置参数
state_dim = 4
k = 100  # 集合大小

# 生成模拟样本矩阵 X_f，shape = (state_dim, k)
X_f = np.random.randn(state_dim, k)

# ===== 方法 1：手动实现公式（2-10）~（2-14） =====
# Step 1: 求均值
x_f_mean = np.mean(X_f, axis=1, keepdims=True)  # shape: (state_dim, 1)

# Step 2: 求偏差矩阵 X_f'
X_f_prime = (X_f - x_f_mean) / np.sqrt(k - 1)

# Step 3: 手动计算协方差矩阵 Pf
P_manual = X_f_prime @ X_f_prime.T

# ===== 方法 2：使用 np.cov =====
P_numpy = np.cov(X_f, bias=False)  # 默认就是除以 (k-1)

# ===== 对比差异 =====
difference = np.abs(P_manual - P_numpy)
max_diff = np.max(difference)

# 输出结果
print("手动计算 Pf:\n", P_manual)
print("\nnp.cov 计算 Pf:\n", P_numpy)
print("\n最大绝对误差:", max_diff)

# 判断是否几乎相等（容忍浮点误差）
if np.allclose(P_manual, P_numpy, atol=1e-10):
    print("\n两种方法结果一致（数值上几乎完全相同）")
else:
    print("\n两种方法结果不一致，请检查实现")


手动计算 Pf:
 [[ 1.23060232 -0.10257449 -0.10770737  0.17950613]
 [-0.10257449  1.01798589  0.15107201  0.06608343]
 [-0.10770737  0.15107201  1.26711545  0.07968793]
 [ 0.17950613  0.06608343  0.07968793  1.2161342 ]]

np.cov 计算 Pf:
 [[ 1.23060232 -0.10257449 -0.10770737  0.17950613]
 [-0.10257449  1.01798589  0.15107201  0.06608343]
 [-0.10770737  0.15107201  1.26711545  0.07968793]
 [ 0.17950613  0.06608343  0.07968793  1.2161342 ]]

最大绝对误差: 2.220446049250313e-16

两种方法结果一致（数值上几乎完全相同）


In [ ]:
iteration: 150 mean: [ 0.5   0.48 -1.26 -0.13 -2.42  3.67 -0.49 11.86] points_result: [-0. -0. -0.  0.  0.  0.  0.  0. -0.  0.]

In [ ]:
noise_t0 = 0.01
noise_t1 = 0.01
noise_t2 = 0.01
noise_t3 = 0.01
noise_t4 = 0.01
noise_t5 = 0.01
noise_t6 = 0.01
noise_t7 = 0.01
noise_t8 = 0.01
noise_t9 = 0.01

delta_t0 = noise_t0**2
delta_t1 = noise_t1**2
delta_t2 = noise_t2**2
delta_t3 = noise_t3**2
delta_t4 = noise_t4**2
delta_t5 = noise_t5**2
delta_t6 = noise_t6**2
delta_t7 = noise_t7**2
delta_t8 = noise_t8**2
delta_t9 = noise_t9**2

phi = np.zeros((m, N))
# 标准差为 delta_v
phi[0] = np.random.normal(loc=0.0, scale=delta_t0, size=N)
phi[1] = np.random.normal(loc=0.0, scale=delta_t1, size=N)
phi[2] = np.random.normal(loc=0.0, scale=delta_t2, size=N)
phi[3] = np.random.normal(loc=0.0, scale=delta_t3, size=N)
phi[4] = np.random.normal(loc=0.0, scale=delta_t4, size=N)
phi[5] = np.random.normal(loc=0.0, scale=delta_t5, size=N)
phi[6] = np.random.normal(loc=0.0, scale=delta_t6, size=N)
phi[7] = np.random.normal(loc=0.0, scale=delta_t7, size=N)
phi[8] = np.random.normal(loc=0.0, scale=delta_t8, size=N)
phi[9] = np.random.normal(loc=0.0, scale=delta_t9, size=N)
